name: CI

# event that triggers workflow
# here when a "push" is made
on: 
  push:

jobs:
  linting-and-testing:
    # specifies the os that the job will run on 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v2
    - uses: chartboost/ruff-action@v1
       
    # sets up python environment with specified versions 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}   
    
    # get rid of DeprecationWarning related to Jupyter paths when running pytest
    - name: Set JUPYTER_PLATFORM_DIRS environment variable
      env:
        JUPYTER_PLATFORM_DIRS: 1
      run: |
        echo "JUPYTER_PLATFORM_DIRS=${JUPYTER_PLATFORM_DIRS}" >> $GITHUB_ENV   

    # installs dependencies from pyproject.toml
    - name: Install dependencies
      run: poetry install --with dev    
    
    - name: Build the project as a package
      run: poetry build

    - name: Create a directory called "test"
      run: mkdir test

    - name: Install the package in the "test" directory
      run: |
        cd test
        pip install ../*.whl

        #- name: Run example scenario
        #run: python examples/cosim_example.py

    # run type checker
    - name: Run type checker
      run: mypy vessim

    # run ruff
    - name: Run linter
      run: ruff .
        
    # run tests
    - name: Run tests
      run: python -m pytest
